apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xdxct-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: xdxct-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: xdxct-device-plugin-ds
    spec:
      # tolerations:
      # - key: xdxct.com/gpu
      #   operator: Exists
      #   effect: NoSchedule
      priorityClassName: "system-node-critical"
      containers:
      # - image: xdxct/k8s-device-plugin:devel
      # xdxct/k8s-device-plugin:devel
      - image: hub.xdxct.com/xdxct-docker/k8s-device-plugin:devel 
        name: xdxct-device-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins

