apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  restartPolicy: Never
  containers:
  - name: pod-xdxsmi
    image: hub.xdxct.com/xdxct-docker/xdxsmi-sample:latest
    command: ["bash", "-c", "xdxsmi"]
    resources:
      limits:
        xdxct.com/gpu: 1
