apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  restartPolicy: OnFailure
  containers:
  - name: pod-xdxsmi
    image: hub.xdxct.com/xdxct-docker/xdxgpu/xdxsmi-sample:1.0.0-Demo-rc-1
    command: ["bash", "-c", "xdxsmi"]
    resources:
      limits:
        xdxct.com/gpu: 1

