apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xdxsmi-demo-ds
spec:
  selector: 
    matchLabels:
      app: xdxsmi-demo 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xdxsmi-demo
    spec:
      containers:
        - env:
            - name: XDXCT_DRIVER_CAPABILITIES
              value: utility
            - name: XDXCT_VISIBLE_DEVICES
              value: all
          image: hub.xdxct.com/xdxct-docker/xdxsmi-sample:latest
          imagePullPolicy: IfNotPresent
          name: xdxsmi-demo
          command: [ "bash","-c","--" ]
          args: [ "while true; do xdxsmi; sleep 600; done;" ]
          stdin: true
          tty: true
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
