apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: glmark2-demo
  name: glmark2-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: glmark2-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: glmark2-demo
    spec:
      containers:
        - env:
            - name: DISPLAY
              value: :0
          image: hub.xdxct.com/xdxct-docker/opengl-sample:latest
          name: glmark2-demo
          resources: 
            limits:
              xdxct.com/gpu: 1
            requests:
              xdxct.com/gpu: 1
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /usr/share/X11/xorg.conf.d/10-xdxgpu.conf
              name: graphics-config
            - mountPath: /tmp/.X11-unix
              name: x11
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: graphics-config
          configMap:
            name: config-files
        - name: x11
          hostPath:
            path: /tmp/.X11-unix/
